spring:
  profiles:
    active: "default"
#    active: "test"
#    active: "prod"
configFile:
  spain:
    td:
      helpdesk:
        routing:
          path: mapConfig/
          name: DynamicRouting_SPAIN_TD.json
        error:
          path: /home/jon/Proyectos/00230056-gal-plus/SRV_CONF_DynamicConf/src/main/resources/mapConfig/
          name: Errors_SPAIN_TD.json
      cdbprovision:
        routing:
          path: mapConfig/
          name: DynamicRouting_SPAIN_TD.json
        error:
          path: /home/jon/Proyectos/00230056-gal-plus/SRV_CONF_DynamicConf/src/main/resources/mapConfig/
          name: Errors_SPAIN_TD.json
      customerprovision:
        routing:
          path: mapConfig/
          name: DynamicRouting_SPAIN_TD.json
        error:
          path: /home/jon/Proyectos/00230056-gal-plus/SRV_CONF_DynamicConf/src/main/resources/mapConfig/
          name: Errors_SPAIN_TD.json